[package]
name = "replicator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
config = { workspace = true, features = ["yaml"] }
pg_replicate = { path = "../pg_replicate", features = ["bigquery"] }
rustls = { workspace = true, features = ["aws-lc-rs", "logging"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
rustls-pemfile = { workspace = true, features = ["std"] }
telemetry = { path = "../telemetry" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true, default-features = true }
